### ISSUE TITLE
rebuycamerasource-debug.aar missing; solution will not compile

### ISSUE THREAD

**Issue by marcusts** [rebuy-de/rb-forms-barcode#58]
Helllo,

Can you add this missing file(s) back to the source?  They prevents compilation of the solution.

rebuycamerasource-debug.aar
rebuycamerasource-release.aar

Stack Trace:

1>------ Rebuild All started: Project: CameraSourceBindings, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(467,5): error MSB4018: The "CreateLibraryResourceArchive" task failed unexpectedly.
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(467,5): error MSB4018: Xamarin.Tools.Zip.ZipIOException: Error occured while reading ..\RebuyCameraSource\RebuyCameraSource\build\outputs\aar\rebuycamerasource-debug.aar
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(467,5): error MSB4018:    at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options)
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(467,5): error MSB4018:    at Xamarin.Android.Tasks.CreateLibraryResourceArchive.Execute()
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(467,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets(467,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by omares** [comment]
Hey @marcusts,

the solution is relatively simple. Open your console and switch into the `RebuyCameraSource` directory of the project. In there execute the `gradle clean build` command. This will build the project and create the asked files:

    **/*.aar
    RebuyCameraSource/build/outputs/aar/rebuycamerasource-debug.aar

**Comment by marcusts** [comment]
Hi,

I tried that, but it required gradle, which I do not have.  The "gradlew.bat" file actually downloaded gradle and tried, but that failed because it needed the java sdk environment variable.   I added that variable, and gradle crashed because it need a specific Java sdk (#23).  I fixed that and gradle crashed because it tried to write to a "garbage" file location made up of odd string segments.  

It would appear that we need someone on your side to just post the proper two filers and not ask to go through these other pre-steps.

I did receive two files from Ota, but they produced several compile and run errors -- "could not open archive" and "moveNext failed".  So these two odd attachments seem to be causing quite a lot of headaches for Windows Visual Studio users.

**Comment by trilm208** [comment]
same issue.any update?

**Comment by omares** [comment]
Hey @trilm208 as rebuy stopped using xamarin we are not actively maintaining this project anymore. Thus there i no update on this issue and no future plans.
